#!/bin/bash
'/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon' &
~/Downloads/kanata_macos_arm64 --cfg ~/.config/kanata/kanata.kbd

